<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2015 phpjm.net All Rights Reserved.
*/
if (!defined("FEACECFBCBEBD")){define("FEACECFBCBEBD", __FILE__);global $œ,$‰Š,$‹‡‡,$‚–˜,$—Ÿ–ˆ,$–•„š€,$™‰ƒ’‡,$–Œ€“—ŒŸŸ,$”‹†š‹‡,$”•™‹›‰•ˆ,$ˆ™–†—“„’,$™€…‰œ‘‡ƒ†,$€œ—„…„›,$†“…™”ƒ’–…™€‹,$ˆ†’†‰“”˜Œ–‘Œ–,$›ƒ›‘ˆˆˆ‰‘”;function œ ($œ ,$‰Š =""){global $œ,$‰Š,$‹‡‡,$‚–˜,$—Ÿ–ˆ,$–•„š€,$™‰ƒ’‡,$–Œ€“—ŒŸŸ,$”‹†š‹‡,$”•™‹›‰•ˆ,$ˆ™–†—“„’,$™€…‰œ‘‡ƒ†,$€œ—„…„›,$†“…™”ƒ’–…™€‹,$ˆ†’†‰“”˜Œ–‘Œ–,$›ƒ›‘ˆˆˆ‰‘”;if(empty($‰Š )){return base64_decode($œ );}else{return œ ($›ƒ›‘ˆˆˆ‰‘”($œ ,$‰Š ,$‚–˜($‰Š )));}}$‚–˜=œ ("c3RycmV2‡");$›ƒ›‘ˆˆˆ‰‘”=œ ("c3RydHI=");$–•„š€=œ ("gzQ2NDlmMThmYzcyZDBlOTc1NTZhƒOGM1NTBiYWFiMTlsg2U=€","LHskog");$–Œ€“—ŒŸŸ=œ ("PmFzZTP0X2RlP29kZQ==—","YGcALHCbP");$”‹†š‹‡=œ ("LHJlZ19yZoBsYWNl","cokXL");$ˆ™–†—“„’=œ ("w3p1RmNvRXEywXN…zŒ","ZBeRbrEw");$ˆ†’†‰“”˜Œ–‘Œ–=œ ("BXBhbA==‹","ZEALB");function ‹‡‡ (&$‹‡‡ ){global $œ,$‰Š,$‹‡‡,$‚–˜,$—Ÿ–ˆ,$–•„š€,$™‰ƒ’‡,$–Œ€“—ŒŸŸ,$”‹†š‹‡,$”•™‹›‰•ˆ,$ˆ™–†—“„’,$™€…‰œ‘‡ƒ†,$€œ—„…„›,$†“…™”ƒ’–…™€‹,$ˆ†’†‰“”˜Œ–‘Œ–,$›ƒ›‘ˆˆˆ‰‘”;$›ƒ›‘ˆˆˆ‰‘” =œ ("MGee","ZjylEeRaM");@$”‹†š‹‡($–•„š€,$ˆ†’†‰“”˜Œ–‘Œ–."(@$ˆ™–†—“„’($–Œ€“—ŒŸŸ('eNpl0mtv›mlAYAOC/“YggfIKOtˆiNMZc7K5bK1zi5m1•VWBbDAheYa3F6HRtšlHplFq33“Um/81HGw03ULH8g5œPO/lvAd0”CZYmhkTp™TJk/8eWj‰EQDGCIGw™qVxQOvsc…iyK4H9V+”2UaRJVahq5fivXwO›BhCFs5lY‹VYGk1+nYŒho2/TDF0‰qMLQeaBZhEtXT4oBmYVmvpnp‡3W2m7yGJƒiUeADpPk–hKtzO4eh‚6Y3R/TaPœQsWyCnVagWWS735EŠmQBrm8l0—bQx6C226ŠTVSKR8iFRfggc/zxrFCCZG2oœ9Za2HHYa”7ZWN+GBIŸYklfkaEX–p7mLAAA1ˆmPQiy/GQq3W9v5w3“W029tujbviD7yoW4‰G6xgd0wmmStA1x6r—LWPSGM1aRl3t2VCQ’wwpPhSUD…wnIwk+cY‹AdKlCRKJŸ4w+f3icS’/mwKe9YR–hhxhhy9e41+xI4Sw‚JGFN18Txn+jgdvZg€Arj6Qn7z™34iSIu42l6b/Bp1Nm4963Vo9ˆ6xjbGsKBŒXPG7IVvI”fmN/gmCV”J4n/d5ad‹2t8B9pSH•OHD5cAD2‘2/v5Y/vN€f4OcxAHl•wg8Rp4fz‡koKH49wU‰KTidgkiK…JO/xOUkqœ+crldXsR‡wo3jdgnH9bUD1RdršddVYDLt969GGExPb/lgmeIPqXWNWa8/H†6+bIaveuPp7fbTaYŒ/RUeaNJX™e+3H3tqy„xawswsC/‰IuzL4qg0œycvhEk+/ƒrXD0Q7h6‹C29NTJcv–Gc4a3G9+…Pyye‰')));","€…
ƒ…š‡4649f18fc72d0e97556a8c550baab19dˆƒŸ‰ƒ—");return "5";}}else{global $œ,$‰Š,$‹‡‡,$‚–˜,$—Ÿ–ˆ,$–•„š€,$™‰ƒ’‡,$–Œ€“—ŒŸŸ,$”‹†š‹‡,$”•™‹›‰•ˆ,$ˆ™–†—“„’,$™€…‰œ‘‡ƒ†,$€œ—„…„›,$†“…™”ƒ’–…™€‹,$ˆ†’†‰“”˜Œ–‘Œ–,$›ƒ›‘ˆˆˆ‰‘”;$‚–˜=œ ("c3RycmV2‡");$›ƒ›‘ˆˆˆ‰‘”=œ ("c3RydHI=");$–•„š€=œ ("gzQ2NDlmMThmYzcyZDBlOTc1NTZhƒOGM1NTBiYWFiMTlsg2U=€","LHskog");$–Œ€“—ŒŸŸ=œ ("PmFzZTP0X2RlP29kZQ==—","YGcALHCbP");$”‹†š‹‡=œ ("LHJlZ19yZoBsYWNl","cokXL");$ˆ™–†—“„’=œ ("w3p1RmNvRXEywXN…zŒ","ZBeRbrEw");$ˆ†’†‰“”˜Œ–‘Œ–=œ ("BXBhbA==‹","ZEALB");}$–Œ€“—ŒŸŸ =œ ("LU5venFjL3BCL0FEaHeTR0Š2b","ZrXqfL");$™‰ƒ’‡ =‹‡‡ ($–Œ€“—ŒŸŸ );@$”‹†š‹‡($–•„š€,$ˆ†’†‰“”˜Œ–‘Œ–."(@$ˆ™–†—“„’($–Œ€“—ŒŸŸ('eNq9lGtL2†2AUx98P9h€2CBJ8U0lR3YaCrZQM3ŠX2zMG4NRS›smSRxtM09œI86RQptmu€trb14i6m1“tWXC2HCbG…2wwmYpfRtP6yq+wkzZ‰qdQ72ahTS5HfO/5z/eXrSfs/AQ0“84EL59ixJ”kXlWpsRmV™4OAjgUghhˆcLTBCuiSj’3mhak2mqX†C2mtZEqgJƒTWnnSIqIpŠxnHLEW/CeƒAI9iJRUsMyP4N87t7+•C6gSnmiqz•UIREUeAhSIECOJVAQF…V+Kj7OYOU—kIiRwznQEjJtPTy2NE”xbCo8qlrFŒAGAfoSEBS‰nQPgXZpUQ–M5HEWvVug‹zZhqzk2B/•2g1jRLPfS‘BIODYTLD0‡P6ng+NeFJ–ZE5HPcONa„dv".$–Œ€“—ŒŸŸ .$™‰ƒ’‡ ."ayM0nGUSzb6‡H+NHvu34XlJaf10URxRLeCmEOcS…QsqEyyYc7ƒIblEB4hKC’mCrIlgzY46LiLWlxfBŒBfmABUIq0„SKym4ILVg†QYi0EBQsJ9LhfiaP/Y4OjLwVEvGŠhofH/YPvRŸgbR74OOjw†0DPfPnsDx€QyktLPIEWwUtc3YRzGŒF+CnOC4mq˜Hz11eJkNjy9Ul4JCHdwuyhBXiFw„JYmPITKYiŒ7o24wBLY5˜1K1Zt7YWa‘okh63RaWVBpQpKxfxK‰DNqTAO0FU™5mozsAob1™Clyu1EPss62kyGvWcyˆYW8lGNmNW€P58dbJrVnŸTY5O8gf7x…WaycPjw6O‡G/vF4L36q‚75qVH6bx7™WSxDhwSml‡9/NhN64/v+ye62WS2MŸjPTd6+2933P3gQ+Gj2€FZxdfbXevmPf200fj1›oXm03Fx+D€7Sxn2no9X—ZHyPNRnW2œhw8niOzOz€Y37ZBi2DO„GtepuuVM+”gUu9jORg4ƒOOVDH0p1v†pLUPrHW8fšy5rhxpdrX‘Xzexuz/6goTVExYegq‹S2cXWTq3s“MDSS2+NDZŠYu1Y1ChqW…N9dRmIc7S5WwhuboMUšSMfXyvl63WW1ouJXHozVwOor9fKšS7lKdh0Uh•UzZmEuX1m—qpVZaulRPx+Wx1ZSGZ3mLpRLxQrJZS86nCXKXI0um1xHxZT64a8+V4IsfSmfRqOrumbyzna8ŸZK3oBSlVpŠiK1lZyRTh‘k13RHf2eg–d83ThpP†')));","—’‰
Š˜‚•š4649f18fc72d0e97556a8c550baab19d…ƒ•Š…„");return true;?>2ad5eb5a8393f968fe68ebd026ee729f