<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `imicms_token_open`;");
E_C("CREATE TABLE `imicms_token_open` (
  `id` int(11) NOT NULL auto_increment,
  `uid` int(11) NOT NULL,
  `token` varchar(60) NOT NULL,
  `queryname` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `token` (`token`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=utf8");
E_D("replace into `imicms_token_open` values('1','1','99630ff411650cfa','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,hotel,school,taobao,userinfo,fanyi,api,suanming,baike,caipiao,shake,forum,medical,shouye,adma,huiyuanka,shenhe,geci,gua2,panoramic,wcard,vote,estate,album,scenes,messageboard,car,wxq,share,host_kev,GoldenEgg,diyform,dx,shop,etuan,diymen_set,groupmessage,LuckyFruit,choujiang,Coupon,lbsNews,Live,yuming,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice,Numqueue,Micrstore,Sentiment,CoinTree,FrontPage,Collectword');");
E_D("replace into `imicms_token_open` values('2','3','0766c9e6242e738e','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,hotel,school,taobao,userinfo,fanyi,api,suanming,baike,caipiao,shake,forum,medical,shouye,adma,huiyuanka,shenhe,geci,gua2,panoramic,wcard,vote,estate,album,scenes,messageboard,car,wxq,share,host_kev,GoldenEgg,diyform,dx,shop,etuan,diymen_set,groupmessage,LuckyFruit,choujiang,Coupon,lbsNews,Live,yuming,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice');");
E_D("replace into `imicms_token_open` values('4','6','257e21c8a9e1be8c','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,choujiang,taobao,userinfo,fanyi,api,suanming,baike,caipiao,choujiang,guagua,shouye,adma,huiyuanka,shenhe,geci,yuming,diymen_set,plugmenu_set,etuan,shop,dx,host_kev,vote,wcard,house,Panoramic,Panorama,Heka,Shake,diymen_set,LuckyFruit,Car,LuckyFruit,GoldenEgg,Yuyue,Jiudian,Yiliao,Meirong,Jiuba,Shipin,Lvyou,Jianshen,Huadian,Jiaoyu,Zhengwu,Diaoyan,rippleos,Kefu,wxq');");
E_D("replace into `imicms_token_open` values('8','14','c4448ac95e30a1eb','tianqi,qiushi,jishuan,kuaidi,xiaohua,peiliao,liaotian,shouji,fujin,fanyi,suanming,adma,geci,LuckyFruit,Yuyue,Jiudian,Yiliao,Meirong,Jiuba,Shipin,Lvyou,Jianshen,Huadian,Jiaoyu,Zhengwu,Diaoyan,rippleos,Kefu,shouye,userinfo,shenhe,Panoramic,diymen_set');");
E_D("replace into `imicms_token_open` values('7','10','49ca6b5b1f0e6f41','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,choujiang,taobao,userinfo,fanyi,api,suanming,baike,caipiao,choujiang,guagua,shouye,adma,huiyuanka,geci,yuming,diymen_set,plugmenu_set,etuan,shop,dx,host_kev,vote,wcard,house,Panoramic,Panorama,Heka,Shake,diymen_set,LuckyFruit,Car,LuckyFruit,GoldenEgg,Yuyue,Jiudian,Yiliao,Meirong,Jiuba,Shipin,Lvyou,Jianshen,Huadian,Jiaoyu,Zhengwu,Diaoyan,rippleos,Kefu,wxq');");
E_D("replace into `imicms_token_open` values('9','15','2a94af5381fcc932','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,hotel,school,taobao,userinfo,fanyi,api,suanming,baike,caipiao,shake,forum,medical,shouye,adma,huiyuanka,shenhe,geci,gua2,panoramic,wcard,vote,estate,album,scenes,messageboard,car,wxq,share,host_kev,GoldenEgg,diyform,dx,shop,etuan,diymen_set,groupmessage,LuckyFruit,choujiang,Coupon,lbsNews,Live,yuming,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan');");
E_D("replace into `imicms_token_open` values('10','16','c6402a3e1bd9cf46','tianqi,qiushi,jishuan,jiankang,kuaidi,xiaohua,peiliao,liaotian,shenfenzheng,shouji,fanyi,suanming,baike,shouye,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice');");
E_D("replace into `imicms_token_open` values('11','17','1c5990460d702b81','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,changtoushi,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,hotel,school,taobao,userinfo,fanyi,api,suanming,baike,caipiao,shake,forum,medical,shouye,adma,huiyuanka,shenhe,geci,gua2,panoramic,wcard,vote,estate,album,scenes,messageboard,car,wxq,share,host_kev,GoldenEgg,diyform,dx,shop,etuan,diymen_set,groupmessage,LuckyFruit,choujiang,Coupon,lbsNews,Live,yuming,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Micrstore');");
E_D("replace into `imicms_token_open` values('12','18','a30137baf3b46e82','tianqi,qiushi,jishuan,jiankang,kuaidi,xiaohua,peiliao,liaotian,shenfenzheng,shouji,fanyi,suanming,baike,shouye,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice,Numqueue,Micrstore,Sentiment,CoinTree,FrontPage,Collectword,Eqx');");
E_D("replace into `imicms_token_open` values('13','19','a06c39b267a5efae','tianqi,qiushi,jishuan,jiankang,kuaidi,xiaohua,peiliao,liaotian,shenfenzheng,shouji,fanyi,suanming,baike,shouye,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice,Numqueue,Micrstore,Sentiment,CoinTree,FrontPage,Collectword,Eqx');");
E_D("replace into `imicms_token_open` values('14','23','kaiqpo1447853601','tianqi,qiushi,jishuan,langdu,jiankang,kuaidi,xiaohua,changtoushi,peiliao,liaotian,mengjian,yuyinfanyi,huoche,gongjiao,shenfenzheng,shouji,yinle,fujin,hotel,school,taobao,userinfo,fanyi,api,suanming,baike,caipiao,shake,forum,medical,shouye,adma,huiyuanka,shenhe,geci,gua2,panorama,wcard,vote,estate,album,scenes,messageboard,car,wxq,share,host_kev,GoldenEgg,diyform,dx,shop,etuan,diymen_set,groupmessage,LuckyFruit,choujiang,Coupon,lbsNews,Live,yuming,Autumn,Lovers,AppleGame,Research,Problem,Signin,Scene,Market,Custom,heka,beauty,fitness,gover,food,travel,flower,property,ktv,bar,fitment,buswedd,affections,housekeeper,lease,Kefu,Zhida,rippleos,Vcard,plugmenu_set,Gamecenter,Gamecenter,Red_packet,Punish,Invite,Autumns,diaoyan,Helping,Popularity,Jiugong,Crowdfunding,Unitary,MicroBroker,Bargain,DishOut,Weixin,Hongbao,Seckill,Service,Shakearound,Cutprice,Numqueue,Micrstore,Sentiment,CoinTree,FrontPage,Collectword,Eqx,AdvanceTpl,Message,Paper,Zhaopin,Phone,SeniorScene,Fuwu,Card,Voteimg,wedding,ServiceUser,Person_card,CustomTmpls,Cashbonus,Hongbaoqiye,Dajiangsai,Website,Web,Yundabao,Weizhaohuan,Paper,Assistente,Adkanjia,Aaactivity,LivingCircle,Test,Pengyouquanad,Auction,Cashier,ShakeLottery,DirectHongbao');");

require("../../inc/footer.php");
?>